---
- name: systemd_helper | Deploy journald configuration
  template:
    src: "systemd_journald.j2"
    dest: "/etc/systemd/journald.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
  - "Restart systemd-journald"
