---
- name: systemd | Deploy journald configuration
  template:
    src: "journald.j2"
    dest: "/etc/systemd/journald.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  when:
  - "hostvars[inventory_hostname]['systemd_journald_settings'] is defined"
  - "hostvars[inventory_hostname]['systemd_journald_settings'] != ''"
  notify: "Restart systemd-journald"
