---
- include_tasks: pre_requisite.yml
- include_tasks: deploy_journald.yml
  when:
  - "hostvars[inventory_hostname]['systemd_journald_settings'] is defined"
  - "hostvars[inventory_hostname]['systemd_journald_settings'] != ''"
- include_tasks: deploy_timedatectl.yml
  when:
  - "hostvars[inventory_hostname]['systemd_tzdata'] is defined"
  - "hostvars[inventory_hostname]['systemd_tzdata'] != ''"
- include_tasks: deploy_vconsole.yml
  when:
  - "hostvars[inventory_hostname]['systemd_vconsole'] is defined"
  - "hostvars[inventory_hostname]['systemd_vconsole'] != ''"
- include_tasks: tmpfiles_executor.yml
- include_tasks: udev_executor.yml
  when:
  - "vars['systemd_udev_rules'] is defined"
- include_tasks: deploy_resolved.yml
  when:
  - "hostvars[inventory_hostname]['systemd_resolved'] is defined"
  - "hostvars[inventory_hostname]['systemd_resolved'] != ''"
- include_tasks: networkd_executor.yml
  when:
  - "vars['systemd_networkd_ifaces'] is defined"
  - "vars['systemd_networkd_ifaces'] != []"
