---
- stat:
    path: "/etc/systemd"
  register: "systemd_stat"
- assert:
    that:
    - "vars['systemd_stat']['stat']['exists'] == True"
    msg: "/etc/systemd not exists, something wrong with this system."
- assert:
    that:
    - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd."
- include_tasks: prereq.d/prereq_systemd_tmpfilesd.yml
- include_tasks: prereq.d/prereq_systemd_udev.yml
- include_tasks: prereq.d/prereq_systemd_resolved.yml
  when:
  - "hostvars[inventory_hostname]['systemd_resolved'] is defined"
  - "hostvars[inventory_hostname]['systemd_resolved'] != ''"
  - "hostvars[inventory_hostname]['systemd_resolved'] |
     json_query(vars['systemd_resolved_make_link']) is defined"
  - "hostvars[inventory_hostname]['systemd_resolved'] |
     json_query(vars['systemd_resolved_make_link']) == 'true'"
  vars:
    systemd_resolved_make_link: "[] | map(&make_link || 'false', @) | [0]"
- include_tasks: prereq.d/prereq_systemd_networkd.yml
  when:
  - "hostvars[inventory_hostname]['systemd_networkd'] is defined"
  - "hostvars[inventory_hostname]['systemd_networkd'] != ''"
