---
- stat:
    path: "/etc/systemd"
  register: "systemd_stat"
- assert:
    that:
    - "vars['systemd_stat']['stat']['exists'] == True"
    msg: "/etc/systemd not exists, something wrong with this system."
- assert:
    that:
    - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd."
- name: systemd_helper | Make tmpfiles.d directory
  file:
    path: "/etc/tmpfiles.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: systemd_helper | Make udev rules.d directory
  file:
    path: "/etc/udev/rules.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: systemd_helper | Set facts about tmpfiles.d
  set_fact:
    systemd_tmpfiles_create: "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] | json_query('[].create[].file_name') }}"
    systemd_tmpfiles_clean: "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] | json_query('[].clean[].file_name') }}"
    systemd_tmpfiles_remove: "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] | json_query('[].remove[].file_name') }}"
  when:
  - "hostvars[inventory_hostname]['systemd_tmpfiles'] is defined"
  - "hostvars[inventory_hostname]['systemd_tmpfiles'] != ''"
- name: systemd_helper | Set facts about udev
  set_fact:
    systemd_udev_rules: "{{ hostvars[inventory_hostname]['systemd_udev'] | json_query('[].file_name') }}"
  when:
  - "hostvars[inventory_hostname]['systemd_udev'] is defined"
  - "hostvars[inventory_hostname]['systemd_udev'] != ''"
- name: systemd_helper | Copy udev syntax check script
  copy:
    src: "rule-syntax-check.py"
    dest: "/tmp/rule-syntax-check.py"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
  - "hostvars[inventory_hostname]['systemd_udev'] is defined"
  - "hostvars[inventory_hostname]['systemd_udev'] != ''"
