---
- name: Restart systemd-journald
  systemd:
    name: "systemd-journald"
    state: "restarted"
- name: Cleanup udev script
  file:
    path: "/tmp/rule-syntax-check.py"
    state: "absent"
- name: Restart systemd-resolved
  systemd:
    name: "systemd-resolved"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['systemd_resolved'] |
     json_query(vars['systemd_resolved_restart']) is defined"
  - "hostvars[inventory_hostname]['systemd_resolved'] |
     json_query(vars['systemd_resolved_restart']) == 'true'"
  vars:
    systemd_resolved_restart: "[] | map(&restart || 'false', @) | [0]"
- name: Restart systemd-networkd
  systemd:
    name: "systemd-networkd"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['systemd_networkd'] |
     json_query(vars['systemd_networkd_restart']) is defined"
  - "hostvars[inventory_hostname]['systemd_networkd'] |
     json_query(vars['systemd_networkd_restart']) == 'true'"
  vars:
    systemd_networkd_restart: "[] | map(&restart || 'false', @) | [0]"
